#!/system/bin/sh
#
# AK Tuning
# @anarkia1976
#

# initialize ak
echo "[ak kernel] initialize boot script" | tee /dev/kmsg

# disable debugging on some modules
echo "0" > /sys/module/kernel/parameters/initcall_debug;
echo "0" > /sys/module/alarm/parameters/debug_mask;
echo "0" > /sys/module/alarm_dev/parameters/debug_mask;
echo "0" > /sys/module/binder/parameters/debug_mask;
echo "0" > /sys/module/xt_qtaguid/parameters/debug_mask;
echo "[ak kernel] disable debug mask" | tee /dev/kmsg

